#!/usr/bin/env bash
# Update the package list
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Get the hostname of the server
HOSTNAME=$(uname -n)

# Configure Nginx with the custom HTTP response header
sudo bash -c "cat > /etc/nginx/sites-available/custom_header <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        return 200 '\$host is being served by: $HOSTNAME\n';
    }

    add_header X-Served-By $HOSTNAME;
}
EOL"

# Remove the default configuration to avoid duplicate default server
sudo rm /etc/nginx/sites-enabled/default

# Create a symbolic link if it doesn't exist, remove and recreate it if it exists
if [ ! -e "/etc/nginx/sites-enabled/custom_header" ]; then
    sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/
else
    sudo rm /etc/nginx/sites-enabled/custom_header
    sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/
fi

# Test the Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo service nginx start
