#!/usr/bin/env bash
# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
# Assign parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4
# Transfer the file using SCP
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/
# Check if scp command was successful
command_succeeded() {
    return $?
}
if command_succeeded; then
    echo "File transferred successfully to $USERNAME@$IP:~/"
else
    echo "Failed to transfer the file."
fi
