#!/usr/bin/env bash
# Update the package list
apt-get -y install software-properties-common

# Install HAProxy
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

# Configure HAProxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 306269-web-01:80 check\n\tserver 306269-web-02:80 check" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
service haproxy restart
