#!/usr/bin/env bash
# Using the while loop to display the time for 12 hours and 59 minutes
hrs=0
while [ $hrs -le 12 ]; do
	echo "Hour: $hrs"
	mins=1
	while [ $mins -le 59 ]; do
	echo "$mins"
	((mins++))
	done
	((hrs++))
done
