#!/usr/bin/env bash
# Update the hosts file
cp /etc/hosts /etc/hosts_backup
sed -i 's/127.0.0.1/127.0.0.2/'  /etc/hosts
sh -c "echo '8.8.8.8 facebook.com' >> /etc/hosts"
cp /etc/hosts_backup /etc/hosts
